package edu.cmu.mutuelle.mutuelle.models;


public class Hospital
{
    private String hospitalId; //Assigned by insurance
    private String hospitalName;
    private String tinNumber;
    private String longitude;
    private String latitude;
    private long hospitalKey; //Autogenerated by DB

    public void setHospitalKey(long hospitalKey){
        this.hospitalKey = hospitalKey;
    }
    public long getHospitalKey(){
        return this.hospitalKey;
    }
    public String getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(String hosID) {
        hospitalId = hosID;
    }

    public String getHospitalName()
    {
        return hospitalName;
    }

    public void setHospitalName(String hosName)
    {
        hospitalName = hosName;
    }

    public String getTinNumber() {
        return tinNumber;
    }

    public void setTinNumber(String tinNo) {
        tinNumber = tinNo;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String lat) {
        latitude = lat;
    }

    public String getLongitude() {
        return latitude;
    }

    public void setLongitude(String longi) {
        longitude = longi;
    }
}
